### ISSUE TITLE
Modify to show all locations for admin user. 

### ISSUE THREAD

**Issue by roydeanjr** [ryanmitchell/ti-ext-runningorder#2]

**Comment by ryanmitchell** [comment]
Also fixed

**Comment by roydeanjr** [comment]
However, what needs to be done to limit the location list to those locations that are enabled. Disabled will not have orders and may not be used every day. I operate a food truck and we move around a lot. The locations we are not at I disable.

**Comment by roydeanjr** [comment]
Thank you, BTW!

**Comment by ryanmitchell** [comment]
Do you mean the location list in TI itself? This extension doesnt list any locations.
