### ISSUE TITLE
Add columns to allow 1 click to set Prep, Ready and then Complete

### ISSUE THREAD

**Issue by roydeanjr** [ryanmitchell/ti-ext-runningorder#3]
And send email to customer for all these changes. I think I have the code, just nothing showing on screen so I can't test.

**Comment by roydeanjr** [comment]
And send email to customer for all these changes. I think I have the code, just nothing showing on screen so I can't test.

**Comment by ryanmitchell** [comment]
It wasn’t my intention to give you a fully functioning piece of custom development :) I was just trying to give you a jumping off point to amend for your use case. 

If you notice issues feel free to open a PR with the change so others can benefit but this isn’t an extension I intend on maintaining.

**Comment by ryanmitchell** [comment]
I should add that I'm happy to take on custom TI development if you need someone to do it for you.

**Comment by roydeanjr** [comment]
What is your fee? I may need that, especially when it comes to redesign of the interface for the KDS, but yes, I can open a PR and do and debug the changes I think I want to make. I am just a real newbie when it comes to Laravel, composer, igniter, etc.

**Comment by ryanmitchell** [comment]
I would agree a project fee for any work and it would depend on the scope.

**Comment by roydeanjr** [comment]
Honestly most of the work is done unless I am mistaken. You have done a great job and I really appreciate your help. I have added code that I think would change the status. I also added columns to hold the buttons, just waiting to test. Will download new code you have put up and see what else I need to do. I'll keep you posted.

**Comment by roydeanjr** [comment]
I have made the changes we spoke about. How do I get those changes into the working system so others can review what we have done and take advantage of our work? Maybe make this a paid extension?

**Comment by ryanmitchell** [comment]
You can open a pull request here with the changes and I’ll test and double check them. 

If you feel it’s valuable we could release it to the marketplace - I’m not sure that there is enough function in it to be a paid extension.

**Comment by roydeanjr** [comment]
If we get the format changed, the email sending working and the menu to gmot show, I think it will serve a great function. And, if we could get TI to read card data from a card reader, that would be very much worth it. Maybe even get little kiosk devices like at Chili's so customers could order from their table. Even cooler!

RoyDean Leighton
At your service......

________________________________

**Comment by ryanmitchell** [comment]
Thanks for the changes, I'll get a proper look over the next few days and come back to you.

I'm probably not prepared to take this extension much further as there are other areas of TI I'm focusing on at the moment. I'm happy for you to keep iterating on it and I will provide feedback and suggestions.

**Comment by roydeanjr** [comment]
Thank you!

RoyDean Leighton
At your service......

________________________________
